import { CheckCircle2, Database, KeyRound, RefreshCw, ShieldCheck, Workflow } from "lucide-react";
import type { ReactNode } from "react";
import { AppShell, StatusBadge } from "../components/AppShell";
import { CommandBlock } from "../components/CommandBlock";
import { to } from "../router";

type Navigate = (route: ReturnType<typeof to.view> | ReturnType<typeof to.landing>) => void;
const Section = ({ id, title, children }: { id: string; title: string; children: ReactNode }) => <section id={id} className="scroll-mt-24 border-b border-border py-10 first:pt-0 last:border-0"><h2 className="text-3xl font-extrabold">{title}</h2><div className="mt-5 space-y-5 text-sm leading-7 text-muted-foreground">{children}</div></section>;
const addresses = [
  ["Succession escrow", "0x642dFC05C9DCC0617c67B318C78dd5AE94134603"],
  ["ERC-8004 registry", "0x7177a6867296406881E20d6647232314736Dd09A"],
  ["USDC payment token", "0x036CbD53842c5426634e7929541eC2318f3dCF7e"],
  ["Independent evaluator", "0x518477058d12e60D74E42b799F5ad0f5c4FFf31b"],
];
const commands = [
  ["inventory", "Show sellable and withheld records by category."], ["prove", "Run an isolated export/import/re-hash before listing."],
  ["list", "Commit a signed root on chain and publish ciphertext."], ["publish", "Resume marketplace publication from the durable vault."],
  ["market", "Browse published listings."], ["show", "Inspect one listing before payment."], ["buy", "Approve the exact price and fund escrow."],
  ["fulfil", "Release eligible content keys from the seller vault."], ["evaluate", "Verify in isolation and submit the evaluator verdict."],
  ["claim", "Import into a fresh buyer tenant and write a certificate."], ["status", "Report local, service, and chain configuration."],
  ["audit", "Verify the product claims; optionally compare chain roots."], ["listings", "Show locally retained seller listing records."],
];
const env = [
  ["SUCCESSION_MARKETPLACE", "Hosted metadata, ciphertext, and authenticated key relay URL."],
  ["BASE_SEPOLIA_RPC_URL", "Base Sepolia JSON-RPC endpoint."], ["SUCCESSION_SIGNING_KEY", "Seller wallet; owns and lists the origin identity."],
  ["SUCCESSION_BUYER_KEY", "Buyer wallet; approves USDC, funds escrow, and claims."], ["SUCCESSION_EVALUATOR_KEY", "Dedicated evaluator wallet configured by the contract."],
  ["SUCCESSION_FINALITY_CONFIRMATIONS", "Receipt depth; defaults to three on Base Sepolia."], ["SUCCESSION_VAULT", "Seller package and content-key recovery directory."],
  ["SUCCESSION_DEPLOYMENT", "Optional path to a deployment record."], ["SUCCESSION_MCP_ALLOW_WRITES", "Must be 1 before MCP tools may mutate files or chain state."],
];

export function Docs({ navigate }: { navigate: Navigate }) {
  return <AppShell current="docs" navigate={navigate}><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
    <header className="border-b border-border pb-7"><p className="text-sm font-extrabold uppercase text-muted-foreground">Technical documentation</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">Succession protocol reference.</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-muted-foreground">Architecture, deployed contracts, memory-package integrity, settlement states, CLI commands, environment configuration, security boundaries, and recovery behavior.</p></header>
    <div className="mt-8 grid gap-8 xl:grid-cols-[16rem_1fr]"><aside className="hidden xl:block"><div className="sticky top-20 rounded-lg border border-border bg-card p-5"><p className="text-xs font-extrabold uppercase text-muted-foreground">Documentation</p><nav className="mt-4 space-y-1 text-sm">{[["architecture","Architecture"],["deployment","Live deployment"],["roles","Roles and workflow"],["integrity","Package integrity"],["lifecycle","Settlement lifecycle"],["commands","CLI reference"],["configuration","Configuration"],["api","HTTP and MCP"],["security","Security model"],["recovery","Recovery and finality"]].map(([id,label]) => <a key={id} href={"#" + id} className="block rounded px-2 py-1.5 font-semibold text-muted-foreground hover:bg-secondary hover:text-foreground">{label}</a>)}</nav><button onClick={() => navigate(to.view("guide"))} className="mt-5 w-full rounded-md bg-primary px-3 py-2 text-sm font-extrabold text-primary-foreground">First-transfer guide</button></div></aside>
      <article className="min-w-0">
        <Section id="architecture" title="Architecture"><p>Succession transfers the durable memory associated with an agent while keeping plaintext processing on role-specific hosts. The chain coordinates value and ERC-8004 ownership; the hosted service distributes public metadata and encrypted packages and relays keys only to authenticated participants.</p><div className="grid gap-3 md:grid-cols-3">{[["Local memory","Sibyl SQLite stores remain on seller, evaluator, and buyer hosts."],["Hosted relay","Metadata and ciphertext are public; content keys are role-gated."],["Base settlement","USDC release, identity transfer, and sealing occur in one transaction."]].map(([title,body]) => <div key={title} className="rounded-md border border-border bg-card p-5"><p className="font-bold text-foreground">{title}</p><p className="mt-2 leading-6">{body}</p></div>)}</div><div className="rounded-lg border border-border bg-foreground p-5 font-mono text-xs leading-7 text-background"><p>seller store → filter → canonical package → Merkle root → seller signature</p><p>signed root → Base listing · encrypted package → hosted relay</p><p>buyer escrow → seller key release → evaluator isolated import + re-hash</p><p>matching verdict → USDC release + ERC-8004 transfer + sealed sale</p><p>buyer claim → transactional import + destination re-hash + certificate</p></div></Section>
        <Section id="deployment" title="Live Base Sepolia deployment"><div className="flex items-center gap-3"><StatusBadge status="live"/><span className="font-semibold text-foreground">Chain ID 84532 · three-confirmation receipt policy</span></div><div className="overflow-hidden rounded-lg border border-border bg-card">{addresses.map(([name,address]) => <div key={name} className="grid gap-1 border-b border-border p-4 last:border-0 sm:grid-cols-[13rem_1fr]"><span className="font-semibold text-foreground">{name}</span><code className="break-all font-mono text-xs">{address}</code></div>)}</div><p>The evaluator address is the only account authorized to submit delivery verdicts. The current deployment uses Circle test USDC and the verified ERC-8004 registry.</p></Section>
        <Section id="roles" title="Roles and workflow"><div className="grid gap-3 md:grid-cols-3">{[["01 · Seller","Proves, signs, encrypts, commits, publishes, and releases the key only after escrow."],["02 · Evaluator","Authenticates delivery, imports into an isolated store, checks signature and root, then settles."],["03 · Buyer","Reviews the commitment, funds escrow, and claims into a fresh destination after settlement."]].map(([title,body]) => <div key={title} className="rounded-lg border border-border bg-card p-5"><Workflow className="h-5 w-5 text-primary"/><p className="mt-5 font-bold text-foreground">{title}</p><p className="mt-2 leading-6">{body}</p></div>)}</div><p>Use separate wallets and separate databases. Evaluator independence is an operational property: its key and destination store must not be controlled by the seller or buyer.</p></Section>
        <Section id="integrity" title="Memory package and integrity model"><p>The Succession Memory Package groups six categories: identity, relationships, preferences, history, commitments, and learned behaviors. Disclosure rules can withhold records. Remaining records are canonicalized deterministically, hashed into category subroots, and combined into one Merkle root.</p><div className="grid gap-3 sm:grid-cols-2">{[["Commitment precedes delivery","The listing root exists before the buyer receives plaintext."],["Whole-header signature","Agent identity, categories, owner history, and root are authenticated together."],["Destination re-hash","The evaluator and buyer derive roots from their imported stores."],["Encrypted transport","AES-256-GCM protects the package; the content key is withheld until escrow."]].map(([title,body]) => <div key={title} className="rounded-md border border-border bg-card p-4"><CheckCircle2 className="h-4 w-4 text-success"/><p className="mt-3 font-bold text-foreground">{title}</p><p className="mt-1 leading-6">{body}</p></div>)}</div></Section>
        <Section id="lifecycle" title="Settlement lifecycle"><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[640px] text-left"><thead className="border-b border-border bg-secondary"><tr><th className="p-4">State</th><th className="p-4">Entered by</th><th className="p-4">Meaning</th></tr></thead><tbody>{[["Open","Seller list","Root committed; identity approval held; no buyer funds."],["Escrowed","Buyer buy","Exact USDC price held by the contract."],["Confirmed","Evaluator verdict","Root matched; payment and identity transferred; sale sealed."],["Refunded","Evaluator mismatch or authorized recovery","Escrow returned; identity remains transferable unless separately settled."]].map(row => <tr key={row[0]} className="border-b border-border last:border-0">{row.map((cell,i) => <td key={cell} className={"p-4 align-top " + (i===0 ? "font-mono font-bold text-foreground" : "")}>{cell}</td>)}</tr>)}</tbody></table></div></Section>
        <Section id="commands" title="CLI command reference"><p>Run <code className="font-mono text-foreground">succession COMMAND --help</code> for all arguments. Mutating chain commands describe their action first unless explicitly passed <code className="font-mono text-foreground">--yes</code>.</p><div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2">{commands.map(([name,body]) => <div key={name} className="bg-card p-4"><code className="font-mono font-bold text-primary">{name}</code><p className="mt-1 leading-6">{body}</p></div>)}</div><CommandBlock>{"succession --help\nsuccession COMMAND --help\nsuccession status\nsuccession audit\nsuccession audit --check-chain"}</CommandBlock></Section>
        <Section id="configuration" title="Environment configuration"><div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[700px] text-left"><thead className="border-b border-border bg-secondary"><tr><th className="p-4">Variable</th><th className="p-4">Purpose</th></tr></thead><tbody>{env.map(([name,body]) => <tr key={name} className="border-b border-border last:border-0"><td className="p-4 font-mono text-xs font-bold text-foreground">{name}</td><td className="p-4">{body}</td></tr>)}</tbody></table></div></Section>
        <Section id="api" title="HTTP service and MCP"><p>The production service exposes read-only health, chain, market, and listing data plus signed seller delivery and buyer/evaluator key endpoints. Administrative routes use a separate API token. Signed requests bind method, path, body, chain, contract, timestamp, and nonce.</p><CommandBlock>{"GET /api/health\nGET /api/chain\nGET /api/market\nGET /api/listing/{listing_id}\nGET /api/listing/{listing_id}/envelope"}</CommandBlock><p>The MCP server starts with <code className="font-mono text-foreground">succession-mcp</code>. Inspection tools are read-only by default. File writes, publication, delivery, and transactions require <code className="font-mono text-foreground">SUCCESSION_MCP_ALLOW_WRITES=1</code>; keys still come from the host environment.</p></Section>
        <Section id="security" title="Security model"><div className="grid gap-3 md:grid-cols-3">{[{Icon:KeyRound,title:"Key custody",body:"Seller, buyer, and evaluator keys stay in their role environments."},{Icon:ShieldCheck,title:"Independent verdict",body:"Only the configured evaluator can settle a delivery."},{Icon:Database,title:"Local stores",body:"Seller and buyer memory stays in separate transactional databases."}].map(({Icon,title,body}) => <div key={title} className="rounded-lg border border-border bg-card p-5"><Icon className="h-5 w-5 text-primary"/><p className="mt-4 font-bold text-foreground">{title}</p><p className="mt-2 leading-6">{body}</p></div>)}</div><p>The contract can prove value movement, identity movement, and the committed/delivered roots. It cannot prevent a filesystem owner from copying a database before sale. Seller retirement is therefore enforced by a durable local seal and operational policy, with on-chain evidence of the handover.</p></Section>
        <Section id="recovery" title="Recovery and finality"><p>Prepared seller assets are fsynced to the vault before listing. The seller watcher can republish a key after relay restart. Buyer imports and acquisition certificates share a durable journal, so repeating claim resumes rather than duplicating records. Use the same listing, database, and tenant during recovery.</p><div className="rounded-md border border-primary/30 bg-primary/10 p-5"><div className="flex gap-3"><RefreshCw className="mt-1 h-5 w-5 shrink-0 text-primary"/><p><strong className="text-foreground">Base Sepolia policy:</strong> transaction commands wait for three confirmations. This is a practical testnet threshold. A mainnet release should additionally reconcile L1-finalized state before irreversible external retirement.</p></div></div><CommandBlock>{"succession publish --listing listing-ID\nsuccession fulfil --listing listing-ID --once\nsuccession claim --listing listing-ID --db buyer.db --tenant successor\nsuccession audit --check-chain"}</CommandBlock></Section>
      </article>
    </div>
  </div></AppShell>;
}
