import { CopyableCodeBlock } from "../components/CopyableCodeBlock";
import { GuideStep } from "../components/GuideStep";
import { SiteHeader } from "../components/SiteHeader";
import { to } from "../router";

type Navigate = (route: ReturnType<typeof to.view> | ReturnType<typeof to.landing>) => void;
export default function Guide({ navigate }: { navigate: Navigate }) {
  return <div><SiteHeader navigate={navigate} /><div className="mx-auto max-w-3xl px-6 pb-24">
    <header className="py-12"><p className="mb-3 font-mono text-xs uppercase tracking-widest text-accent">CLI · role-separated custody</p><h1 className="text-balance font-display text-3xl font-bold">Run Succession from your terminal.</h1><p className="mt-4 max-w-2xl text-[15px] leading-relaxed text-ink/80">The seller, evaluator, and buyer each operate beside their own wallet and local Sibyl store. The browser is a read-only deployment dashboard.</p></header>
    <GuideStep n={1} title="Install Succession"><p className="text-sm text-ink/75">Install the CLI with chain support, then point it at the live Railway service and Base Sepolia.</p><CopyableCodeBlock>{`pipx install "succession-cli[chain,mcp]"\nexport SUCCESSION_MARKETPLACE=https://succession-production-7320.up.railway.app\nexport BASE_SEPOLIA_RPC_URL=https://sepolia.base.org`}</CopyableCodeBlock></GuideStep>
    <GuideStep n={2} title="Verify the connection"><CopyableCodeBlock>{`succession status\nsuccession audit --check-chain`}</CopyableCodeBlock></GuideStep>
    <GuideStep n={3} title="Inspect and prove the seller store"><p className="text-sm text-ink/75">The round trip uses an isolated destination before any transaction is sent.</p><CopyableCodeBlock>{`export SUCCESSION_SIGNING_KEY=0x…\nsuccession inventory --db seller.db --tenant seller-agent\nsuccession prove --db seller.db --tenant seller-agent \\\n  --agent erc8004:84532:YOUR_AGENT_ID`}</CopyableCodeBlock></GuideStep>
    <GuideStep n={4} title="Commit and fund"><p className="text-sm text-ink/75">The seller commits first. A separate buyer reviews the dry run before broadcasting.</p><CopyableCodeBlock>{`succession list --db seller.db --tenant seller-agent \\\n  --agent erc8004:84532:YOUR_AGENT_ID --price 1000000\n\nexport SUCCESSION_BUYER_KEY=0x…\nsuccession buy --listing listing-YOUR_ID\nsuccession buy --listing listing-YOUR_ID --yes`}</CopyableCodeBlock></GuideStep>
    <GuideStep n={5} title="Evaluate independently"><p className="text-sm text-ink/75">The evaluator imports into its own empty tenant and alone submits the verdict.</p><CopyableCodeBlock>{`succession fulfil --listing listing-YOUR_ID --once\n\nexport SUCCESSION_EVALUATOR_KEY=0x…\nsuccession evaluate --listing listing-YOUR_ID \\\n  --db evaluator.db --tenant isolated --yes`}</CopyableCodeBlock></GuideStep>
    <GuideStep n={6} title="Claim and verify"><CopyableCodeBlock>{`succession claim --listing listing-YOUR_ID \\\n  --db buyer.db --tenant successor\nsuccession inventory --db buyer.db --tenant successor`}</CopyableCodeBlock></GuideStep>
    <GuideStep n={7} title="Recover after interruption"><p className="text-sm leading-relaxed text-ink/80">Restart the seller watcher from its durable vault and repeat claim against the same buyer destination. Both paths are replay-safe.</p><CopyableCodeBlock>{`succession fulfil --listing listing-YOUR_ID --once\nsuccession claim --listing listing-YOUR_ID \\\n  --db buyer.db --tenant successor`}</CopyableCodeBlock><button onClick={() => navigate(to.view("terminal"))} className="font-mono text-sm text-accent hover:underline">Open the video runbook →</button></GuideStep>
  </div></div>;
}
