import { AlertTriangle, CheckCircle2 } from "lucide-react";
import type { ReactNode } from "react";
import { AppShell } from "../components/AppShell";
import { CommandBlock } from "../components/CommandBlock";
import { to } from "../router";

type Navigate = (route: ReturnType<typeof to.view> | ReturnType<typeof to.landing>) => void;
const Card = ({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: ReactNode }) => <section id={id} className="scroll-mt-24 rounded-lg border border-border bg-card p-6 shadow-panel sm:p-8"><p className="text-xs font-extrabold uppercase text-primary">{eyebrow}</p><h2 className="mt-2 text-2xl font-extrabold sm:text-3xl">{title}</h2><div className="mt-4 space-y-4 text-sm leading-7 text-muted-foreground">{children}</div></section>;

export function Guide({ navigate }: { navigate: Navigate }) {
  return <AppShell current="guide" navigate={navigate}><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
    <header className="border-b border-border pb-7"><p className="text-sm font-extrabold uppercase text-muted-foreground">Complete beginner guide</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">Install Succession and make your first transfer.</h1><p className="mt-3 max-w-3xl text-lg leading-8 text-muted-foreground">From a clean machine to a verified Base Sepolia handover: installation, help commands, wallet roles, memory preparation, escrow, evaluation, import, and recovery.</p></header>
    <div className="mt-6 grid gap-3 sm:grid-cols-4">{[["01","Install"],["02","Prepare"],["03","Transfer"],["04","Verify"]].map(([n,label]) => <div key={n} className="rounded-md border border-border bg-card p-4"><span className="font-mono text-xs font-bold text-primary">{n}</span><p className="mt-1 font-bold">{label}</p></div>)}</div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_18rem]"><div className="space-y-5">
      <Card id="requirements" eyebrow="Before you begin" title="What you need"><p>Use Python 3.11 or newer. A local audit needs no wallet or network. A live transfer needs a Base Sepolia RPC URL, separate seller and buyer wallets with test ETH, buyer test USDC, a seller-owned ERC-8004 identity, and access to the configured independent evaluator.</p><div className="grid gap-3 sm:grid-cols-2">{["Python 3.11+ and pipx","A local Sibyl memory database","Base Sepolia ETH for each signer","Test USDC in the buyer wallet","Seller-owned ERC-8004 agent","Separate evaluator key custody"].map(item => <p key={item} className="flex gap-2 rounded-md border border-border bg-background/50 p-3 text-foreground"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-success"/>{item}</p>)}</div></Card>
      <Card id="install" eyebrow="Step 1" title="Install the Succession CLI"><p>For normal use, install the published CLI in an isolated environment with <strong className="text-foreground">pipx</strong>. The <code className="font-mono text-foreground">chain</code> extra enables Base transactions and <code className="font-mono text-foreground">mcp</code> enables agent-tool integration.</p><CommandBlock>{"python3 --version\npython3 -m pip install --user pipx\npython3 -m pipx ensurepath\npipx install \"succession-cli[chain,mcp]\""}</CommandBlock><p>To work from source instead, clone the repository and create its virtual environment:</p><CommandBlock>{"git clone https://github.com/linoxbt/Succession.git\ncd Succession\npython3 -m venv .venv\n.venv/bin/pip install -e \"packages/succession[chain,mcp]\"\n.venv/bin/succession --help"}</CommandBlock></Card>
      <Card id="help" eyebrow="Step 2" title="Learn the CLI before sending transactions"><p>A bare command gives the guided overview. Every command has focused help. Start with status and the offline self-audit; the audit constructs, transfers, imports, and re-hashes deterministic test memory without spending gas.</p><CommandBlock>{"succession\nsuccession --help\nsuccession list --help\nsuccession claim --help\nsuccession status\nsuccession audit"}</CommandBlock><div className="rounded-md border border-primary/30 bg-primary/10 p-4 text-foreground"><strong>Expected audit result:</strong> seven passing claims and a zero exit code. Add <code className="font-mono">--check-chain</code> when the marketplace and Base Sepolia RPC are configured.</div></Card>
      <Card id="configure" eyebrow="Step 3" title="Configure network and role-specific keys"><p>Set public endpoints in every role terminal. Load exactly one signing role per host or terminal. Keep keys in a mode-600 environment file or a secret manager; never pass a private key as a CLI argument.</p><CommandBlock>{"export SUCCESSION_MARKETPLACE=https://succession-production-7320.up.railway.app\nexport BASE_SEPOLIA_RPC_URL=https://sepolia.base.org\nexport SUCCESSION_FINALITY_CONFIRMATIONS=3"}</CommandBlock><div className="grid gap-3 md:grid-cols-3">{[["Seller","SUCCESSION_SIGNING_KEY","Owns the ERC-8004 identity and commits the package."],["Buyer","SUCCESSION_BUYER_KEY","Holds test USDC, funds escrow, and authenticates claim."],["Evaluator","SUCCESSION_EVALUATOR_KEY","Receives the pre-settlement key and submits the verdict."]].map(([role,key,body]) => <div key={role} className="rounded-md border border-border bg-background/50 p-4"><p className="font-bold text-foreground">{role}</p><code className="mt-2 block break-all font-mono text-xs text-primary">{key}</code><p className="mt-2 leading-6">{body}</p></div>)}</div><p className="flex gap-2 rounded-md border border-warning/40 bg-warning/10 p-4 text-foreground"><AlertTriangle className="mt-1 h-4 w-4 shrink-0"/>Never put seller, buyer, or evaluator keys in the web frontend, command history, screenshots, recordings, or a shared host.</p></Card>
      <Card id="prepare" eyebrow="Step 4" title="Inspect and prove the seller memory"><p>The seller starts with a Sibyl SQLite database and tenant. Inventory reports records available in each category and anything withheld by disclosure policy. Prove exports the chosen scope, imports it into an isolated temporary store, then compares every destination subroot.</p><CommandBlock>{"succession inventory --db seller.db --tenant seller-agent\nsuccession prove --db seller.db --tenant seller-agent \\\n  --agent erc8004:84532:YOUR_AGENT_ID"}</CommandBlock><p>Do not continue until the output says <strong className="text-foreground">verified YES</strong>. For a partial transfer, prove and list the identical scope, such as <code className="font-mono text-foreground">--scope relationships=60,history=100</code>.</p></Card>
      <Card id="list" eyebrow="Step 5 · Seller" title="Commit and publish the package"><p>Listing builds the consent-filtered package locally, signs its complete provenance header, encrypts it, writes the recovery vault, approves the escrow contract for the identity, and commits the Merkle root on Base before publishing ciphertext.</p><CommandBlock>{"succession list --db seller.db --tenant seller-agent \\\n  --agent erc8004:84532:YOUR_AGENT_ID --price 1000000"}</CommandBlock><p>USDC uses six decimal places, so <code className="font-mono text-foreground">1000000</code> is 1 USDC. Save the printed listing ID. If publishing fails after the chain transaction, recover with <code className="font-mono text-foreground">succession publish --listing listing-ID</code>; do not run <code className="font-mono text-foreground">list</code> again.</p></Card>
      <Card id="buy" eyebrow="Step 6 · Buyer" title="Inspect and fund escrow"><p>The buyer reviews the data-room metadata and the committed root. Run buy without <code className="font-mono text-foreground">--yes</code> first: it shows the seller, price, buyer, and two planned transactions without broadcasting.</p><CommandBlock>{"succession show --listing listing-YOUR_ID\nsuccession buy --listing listing-YOUR_ID\nsuccession buy --listing listing-YOUR_ID --yes"}</CommandBlock><p>The live command approves exactly the listing price and funds escrow. Payment stays in the contract until evaluator settlement or an authorized refund.</p></Card>
      <Card id="evaluate" eyebrow="Steps 7–8 · Seller and evaluator" title="Release, independently verify, and settle"><p>After escrow is funded, the seller releases the content key to the authenticated relay. The evaluator collects it, decrypts the package, verifies the seller signature, imports into a separate database, and re-derives the root.</p><CommandBlock>{"# Seller terminal\nsuccession fulfil --listing listing-YOUR_ID --once\n\n# Evaluator terminal: inspect verdict, then broadcast it\nsuccession evaluate --listing listing-YOUR_ID \\\n  --db evaluator.db --tenant isolated\nsuccession evaluate --listing listing-YOUR_ID \\\n  --db evaluator.db --tenant isolated --yes"}</CommandBlock><p>A matching evaluator root atomically releases USDC, transfers the ERC-8004 identity to the buyer wallet, and seals the sale. A mismatched delivery refunds instead.</p></Card>
      <Card id="claim" eyebrow="Step 9 · Buyer" title="Claim into the successor store"><p>Only after evaluator settlement can the buyer endpoint release the key. Claim imports transactionally, re-hashes the buyer database, and writes a durable acquisition certificate. Use a fresh tenant.</p><CommandBlock>{"succession claim --listing listing-YOUR_ID \\\n  --db buyer.db --tenant successor \\\n  --successor-agent erc8004:84532:SUCCESSOR_AGENT_ID\nsuccession inventory --db buyer.db --tenant successor"}</CommandBlock><p>The certificate names both agents, record count, categories, root, seller signature, settlement transaction, and transfer status.</p></Card>
      <Card id="verify" eyebrow="Step 10" title="Verify, retry, and recover"><p>Finish by comparing published roots with Base. Repeating fulfil or claim with the same listing and destination is safe: seller vault and buyer acquisition journals resume interrupted work without duplicating settlement or imported records.</p><CommandBlock>{"succession audit --check-chain\nsuccession listings\nsuccession fulfil --listing listing-YOUR_ID --once\nsuccession claim --listing listing-YOUR_ID \\\n  --db buyer.db --tenant successor \\\n  --successor-agent erc8004:84532:SUCCESSOR_AGENT_ID"}</CommandBlock><p>If a key disappears during a service restart, run fulfil again from the seller host. If buyer completion stops after import, repeat claim against the same database and tenant. Never switch destinations during recovery.</p></Card>
    </div><aside className="hidden xl:block"><div className="sticky top-20 rounded-lg border border-border bg-card p-5"><p className="text-xs font-extrabold uppercase text-muted-foreground">On this page</p><nav className="mt-4 space-y-2 text-sm">{[["requirements","Requirements"],["install","Install CLI"],["help","Help and audit"],["configure","Configure roles"],["prepare","Prepare memory"],["list","List"],["buy","Buy"],["evaluate","Evaluate"],["claim","Claim"],["verify","Recovery"]].map(([id,label]) => <a key={id} href={"#" + id} className="block rounded px-2 py-1.5 font-semibold text-muted-foreground hover:bg-secondary hover:text-foreground">{label}</a>)}</nav><button onClick={() => navigate(to.view("docs"))} className="mt-5 w-full rounded-md bg-foreground px-3 py-2 text-sm font-bold text-background">Open technical docs</button></div></aside></div>
  </div></AppShell>;
}
