"""The neutral record shapes an SMP package is built from.

Succession is only a protocol if the format outlives the engine underneath it.
Everything above this module works on the plain dicts defined here; the Sibyl
adapter next door is the reference implementation that produces them, and a
second engine becomes a second adapter rather than a second export pipeline.

Records deliberately keep engine-assigned identifiers (``id``) separate from
logical keys (``category``/``name``, ``key``). The logical key is what the
integrity commitment binds to, because it is what survives a re-import; the
engine id is regenerated by the destination store and is not hashed.
"""

from __future__ import annotations

from typing import Any, Iterable, Protocol, runtime_checkable

__all__ = [
    "TIERS",
    "MemorySource",
    "MemorySink",
    "entity_record",
    "event_record",
    "state_record",
    "reference_record",
    "archived_record",
    "relation_record",
]

#: The five Sibyl tiers, and the sixth structural table that joins WARM entities.
#: A "full export" in the spec's sense means every one of these travels.
TIERS = (
    "state",       # HOT
    "entity",      # WARM
    "relation",    # WARM (edges)
    "event",       # COLD
    "reference",   # REFERENCE
    "archived",    # ARCHIVE
)


def entity_record(
    *,
    category: str,
    name: str,
    body: Any,
    status: str | None = None,
    created_at: str | None = None,
    updated_at: str | None = None,
    id: str | None = None,
) -> dict[str, Any]:
    return {
        "kind": "entity",
        "id": id,
        "category": category,
        "name": name,
        "status": status,
        "body": body,
        "created_at": created_at,
        "updated_at": updated_at,
    }


def event_record(
    *,
    id: str,
    ts: str,
    evaluated: Any = None,
    acted: Any = None,
    forward: Any = None,
    extra: Any = None,
) -> dict[str, Any]:
    return {
        "kind": "event",
        "id": id,
        "ts": ts,
        "evaluated": evaluated,
        "acted": acted,
        "forward": forward,
        "extra": extra,
    }


def state_record(*, key: str, body: Any, updated_at: str | None = None) -> dict[str, Any]:
    return {"kind": "state", "key": key, "body": body, "updated_at": updated_at}


def reference_record(
    *, key: str, body: Any, metadata: Any = None, updated_at: str | None = None
) -> dict[str, Any]:
    return {
        "kind": "reference",
        "key": key,
        "body": body,
        "metadata": metadata,
        "updated_at": updated_at,
    }


def archived_record(
    *,
    category: str,
    name: str,
    body: Any,
    archive_reason: str | None = None,
    archived_at: str | None = None,
    id: str | None = None,
) -> dict[str, Any]:
    return {
        "kind": "archived",
        "id": id,
        "category": category,
        "name": name,
        "body": body,
        "archive_reason": archive_reason,
        "archived_at": archived_at,
    }


def relation_record(
    *,
    from_key: tuple[str, str],
    to_key: tuple[str, str],
    relation_type: str,
    metadata: Any = None,
    created_at: str | None = None,
) -> dict[str, Any]:
    """An edge between two entities.

    Endpoints are carried as logical ``(category, name)`` keys rather than the
    source store's row ids. Row ids are regenerated on import, so an edge stored
    by id would dangle the moment it landed in the buyer's tenant.
    """
    return {
        "kind": "relation",
        "from_key": list(from_key),
        "to_key": list(to_key),
        "relation_type": relation_type,
        "metadata": metadata,
        "created_at": created_at,
    }


@runtime_checkable
class MemorySource(Protocol):
    """Everything the export pipeline needs to read out of a tenant."""

    @property
    def tenant_id(self) -> str: ...

    def entities(self) -> list[dict[str, Any]]: ...
    def events(self) -> list[dict[str, Any]]: ...
    def states(self) -> list[dict[str, Any]]: ...
    def references(self) -> list[dict[str, Any]]: ...
    def archived(self) -> list[dict[str, Any]]: ...
    def relations(self) -> list[dict[str, Any]]: ...


@runtime_checkable
class MemorySink(Protocol):
    """Everything the import pipeline needs to write into a fresh tenant."""

    @property
    def tenant_id(self) -> str: ...

    def is_empty(self) -> bool: ...
    def write_entities(self, records: Iterable[dict[str, Any]]) -> int: ...
    def write_events(self, records: Iterable[dict[str, Any]]) -> int: ...
    def write_states(self, records: Iterable[dict[str, Any]]) -> int: ...
    def write_references(self, records: Iterable[dict[str, Any]]) -> int: ...
    def write_archived(self, records: Iterable[dict[str, Any]]) -> int: ...
    def write_relations(self, records: Iterable[dict[str, Any]]) -> int: ...
