import { ArrowRight, PlayCircle, Sparkles } from "lucide-react";
import { LogoMark } from "../components/AppShell";
import { to } from "../router";

type Navigate = (route: ReturnType<typeof to.view> | ReturnType<typeof to.landing>) => void;
export function Landing({ navigate }: { navigate: Navigate }) {
  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <section className="shelby-surface relative min-h-[92vh] overflow-hidden text-foreground">
      <img src="/editorial-memory-studio.jpg" alt="Editorial deployment studio" width="1600" height="1000" className="absolute inset-0 h-full w-full object-cover opacity-[0.16] mix-blend-multiply" />
      <div className="absolute inset-0 bg-background/35" />
      <header className="relative z-10 mx-auto max-w-7xl px-5 py-6 sm:px-8"><div className="flex items-center justify-between"><LogoMark navigate={navigate} /><nav className="hidden items-center gap-7 text-sm font-extrabold uppercase text-foreground sm:flex"><button onClick={() => navigate(to.view("guide"))} className="transition hover:opacity-70">Guide</button><button onClick={() => navigate(to.view("docs"))} className="transition hover:opacity-70">Docs</button><button onClick={() => navigate(to.view("dashboard"))} className="transition hover:opacity-70">Dashboard</button></nav><button onClick={() => navigate(to.view("dashboard"))} className="rounded-md bg-primary px-3 py-2 text-sm font-bold text-primary-foreground sm:hidden">Dashboard</button></div><nav className="mt-5 grid grid-cols-2 gap-2 text-sm font-bold sm:hidden"><button onClick={() => navigate(to.view("guide"))} className="rounded-md border border-foreground/20 bg-card/65 px-3 py-2 text-center text-foreground backdrop-blur transition hover:border-primary">Guide</button><button onClick={() => navigate(to.view("docs"))} className="rounded-md bg-primary px-3 py-2 text-center text-primary-foreground transition hover:bg-primary-hover">Docs</button></nav></header>
      <div className="relative z-10 mx-auto grid min-h-[76vh] max-w-7xl content-center px-5 pb-24 pt-12 text-center sm:px-8"><div className="mx-auto max-w-5xl animate-fade-in"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-card/70 px-3 py-1.5 text-sm font-semibold text-foreground shadow-panel backdrop-blur"><Sparkles className="h-4 w-4" /> Powered by Sibyl Memory · settled on Base</div><h1 className="text-balance text-5xl font-extrabold leading-none tracking-normal text-foreground sm:text-6xl lg:text-7xl">Transfer memory with verifiable ownership.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">A complete workflow for agent memory: signed packages, independent destination verification, evaluator-gated settlement, and ERC-8004 identity transfer.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={() => navigate(to.view("dashboard"))} className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-6 py-4 text-sm font-extrabold text-primary-foreground shadow-glow transition hover:bg-primary-hover focus:outline-none focus:ring-2 focus:ring-ring">Open Dashboard <ArrowRight className="h-4 w-4" /></button><a href="/succession-marketing-demo.mp4" className="inline-flex items-center justify-center gap-2 rounded-md border border-foreground/20 bg-card/75 px-6 py-4 text-sm font-extrabold text-foreground backdrop-blur transition hover:border-primary hover:text-primary"><PlayCircle className="h-4 w-4" />Watch Demo</a><button onClick={() => navigate(to.view("guide"))} className="inline-flex items-center justify-center rounded-md border border-foreground/20 bg-card/65 px-6 py-4 text-sm font-extrabold text-foreground backdrop-blur transition hover:border-primary hover:text-primary">Read the Guide</button></div></div></div>
    </section>

    <section className="border-y border-border bg-card px-5 py-7"><div className="mx-auto grid max-w-7xl gap-4 text-center sm:grid-cols-3">{[["7/7","live audit checks"],["7","accepted testnet sales"],["3","finality confirmations"]].map(([number,label]) => <p key={label} className="text-muted-foreground"><span className="font-mono text-xl font-bold text-foreground">{number}</span> {label}</p>)}</div></section>

    <section className="border-y border-border bg-card px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-extrabold uppercase text-primary">Release evidence</p><h2 className="mt-3 text-3xl font-extrabold text-foreground">The Base Sepolia workflow is live and independently checkable.</h2></div><div className="grid gap-3 sm:grid-cols-2">{["Evaluator-gated delivery","Destination re-hash","Two-host restart recovery","Three-confirmation policy","ERC-8004 transfer","Independent contract review"].map(item => <div key={item} className="rounded-md border border-border bg-background/50 p-4"><p className="font-bold text-foreground">{item}</p><p className="mt-1 text-sm text-muted-foreground">Documented with reproducible commands and transaction evidence.</p></div>)}</div></div></section>
    <footer className="border-t border-border bg-sidebar px-5 py-8 text-sm text-muted-foreground sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><LogoMark navigate={navigate} /><p>powered by Sibyl Memory · Base · ERC-8004</p></div></footer>
  </main>;
}
