/**
 * Recorded mode.
 *
 * The pipeline is Python, so a static host has no backend to talk to. Rather
 * than deploy a UI that only shows a connection error, the hosted build replays
 * `public/recorded-run.json` — the captured output of one real end-to-end run:
 * a genuine export, a genuine Merkle root, the seller's genuine signature, the
 * genuine agent replies from the buyer's cold store, and a genuine rejected
 * write against the sealed tenant.
 *
 * Two rules make this honest rather than a mock-up, and both are load-bearing:
 *
 * 1. **Every value is real output.** Nothing here is hand-written to look
 *    plausible. The artifact is regenerated by running the pipeline, and the
 *    root in it is reproducible — `python -m succession.demo` prints the same
 *    one, because the export is deterministic.
 * 2. **The UI says so, permanently.** A banner names the mode and the recording
 *    date on every screen. A recorded run presented as a live one would be
 *    exactly the smoke-and-mirrors pattern this project is built to avoid.
 *
 * What recorded mode cannot do, and does not pretend to: it cannot transfer a
 * category selection you pick here, because the recorded run sold all six.
 * Selecting a subset switches you to a notice explaining that, rather than
 * quietly replaying the full-succession numbers under a partial-sale heading.
 */
import { ApiError } from "./api";
import type { Listing, MarketRow, Outcome, Preview, Reply } from "./api";

/** One row of the settlement ledger, as `scripts/run_transfers.py` writes it. */
export interface RecordedTransfer {
  index: number;
  agent_id: string;
  listing_id: string;
  outcome: "verified" | "refunded";
  committed_root: string;
  delivered_root: string;
  tx: string;
  explorer?: string;
  intentionally_corrupted?: boolean;
}

export interface RecordedRun {
  recorded_at: string;
  source: string;
  listing_open: Listing;
  listing_escrowed: Listing;
  preview: Preview;
  outcome: Outcome;
  replies: Record<string, Reply>;
  write_attempt: { accepted: boolean; reason: string };
  seal: { sealed: boolean; at: string };
  /** Present once a real run has been recorded against a deployment. */
  transfers?: RecordedTransfer[];
  /** Every listing captured at record time, with its computed preview. */
  marketplace?: MarketRow[];
}

let cached: Promise<RecordedRun> | null = null;

export function loadRecordedRun(): Promise<RecordedRun> {
  cached ??= fetch("recorded-run.json").then((r) => {
    if (!r.ok) throw new Error(`recorded run unavailable (${r.status})`);
    return r.json() as Promise<RecordedRun>;
  });
  return cached;
}

/**
 * True when the service is reachable.
 *
 * A 200 is not enough to conclude that. Both the dev server and any static host
 * rewrite unknown paths to the SPA shell, so `/api/health` answers 200 with
 * HTML when no backend exists at all — probing on `response.ok` alone reports a
 * live service everywhere and the recorded fallback never engages. The probe
 * therefore requires the service's actual JSON payload.
 */
export async function probeLiveApi(): Promise<boolean> {
  try {
    const response = await fetch("/api/health", {
      signal: AbortSignal.timeout(2500),
      headers: { Accept: "application/json" },
    });
    if (!response.ok) return false;
    if (!response.headers.get("content-type")?.includes("application/json")) {
      return false;
    }
    return ((await response.json()) as { status?: string }).status === "ok";
  } catch {
    return false;
  }
}

/**
 * The same surface as `api`, served from the recording.
 *
 * `reset` deliberately rejects a partial selection: replaying a full-succession
 * package under a partial-sale heading would misstate what was transferred, and
 * the categories are the one thing a viewer can change here.
 */
export function recordedApi(run: RecordedRun) {
  // The recording is a finished sale, but the UI walks through it a step at a
  // time. Without a phase here `listing()` keeps answering "open" after
  // settlement, so the escrow panel never advances and the console shows a
  // "fund escrow" button beside a completed transfer.
  let phase: "open" | "escrowed" | "confirmed" = "open";

  const listingFor = (): Listing => {
    if (phase === "open") return run.listing_open;
    if (phase === "escrowed") return run.listing_escrowed;
    return {
      ...run.listing_escrowed,
      state: run.outcome.outcome === "verified" ? "confirmed" : "refunded",
      escrow_balance: 0,
      delivered_hash: run.outcome.delivered_root,
      sealed: run.outcome.outcome === "verified",
      settled_at: run.outcome.receipt?.settled_at ?? "",
    };
  };

  return {
    reset: async (categories?: string[]) => {
      if (categories && categories.length < 6) {
        throw new Error(
          "This is a recorded run of a full succession, so a partial selection " +
            "cannot be replayed — the package on file transferred all six " +
            "categories. Run the service locally to transfer a subset.",
        );
      }
      phase = "open";
      return { listing_id: run.listing_open.listing_id, committed_root: run.outcome.committed_root };
    },
    listing: async () => listingFor(),
    marketplace: async () => ({
      listings: run.marketplace ?? [],
      count: run.marketplace?.length ?? 0,
    }),
    preview: async () => run.preview,
    buy: async () => {
      phase = "escrowed";
      return listingFor();
    },
    transfer: async () => {
      phase = "confirmed";
      return run.outcome;
    },
    // The recorded run replays from the start on every load, so before its
    // settlement beat there is no outcome to recover — the same 404 the live
    // service gives for a sale that has not settled.
    outcome: async (): Promise<Outcome> => {
      if (phase !== "confirmed") throw new ApiError("has not settled", 404);
      return run.outcome;
    },
    // The seller is sealed by the sale, so before settlement it is not sealed.
    seal: async () => ({
      sealed: phase === "confirmed" && run.seal.sealed,
      record:
        phase === "confirmed" && run.seal.sealed
          ? { sealed_at: run.seal.at, reason: "memory asset sold" }
          : null,
    }),
    // Before the sale completes the seller can still write; the recorded
    // rejection only becomes true once the tenant is sealed.
    writeAttempt: async () =>
      phase === "confirmed"
        ? run.write_attempt
        : { accepted: true, reason: "tenant is not sealed; the sale has not completed" },
    message: async (_side: "seller" | "buyer", message: string): Promise<Reply> => {
      if (phase !== "confirmed") {
        return {
          text: "I have no memory yet. This agent has not been booted against a transferred store.",
          recalled: false,
          citations: [],
        };
      }
      const exact = run.replies[message];
      if (exact) return exact;
      // Match the recorded prompts by counterparty rather than by string, so a
      // viewer who retypes a question still gets that question's real answer.
      const needle = message.toLowerCase();
      for (const [prompt, reply] of Object.entries(run.replies)) {
        const subject = prompt.match(/(Northwind Mills|Selkirk Timber|Acme Widgets)/i)?.[0];
        if (subject && needle.includes(subject.toLowerCase())) return reply;
      }
      return {
        text:
          "This is a recorded run, so only the three counterparties below have " +
          "captured answers. Run the service locally to query the transferred " +
          "memory freely.",
        recalled: false,
        citations: [],
      };
    },
  };
}
