import { ChevronDown, Database, ExternalLink, ShieldCheck } from "lucide-react";
import { Fragment } from "react";
import { useState } from "react";
import { provenanceSales } from "../data/provenanceSales";

const short = (value: string) => value.length > 22 ? value.slice(0, 12) + "…" + value.slice(-8) : value;

export function ProvenanceLedger() {
  const [selected, setSelected] = useState<string | null>(provenanceSales[0]?.listingId ?? null);
  return <section className="mt-8 overflow-hidden rounded-lg border border-border bg-card shadow-panel">
    <header className="flex flex-col gap-4 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-extrabold uppercase text-primary"><Database className="h-4 w-4"/>Sibyl Memory provenance</div><h2 className="mt-2 text-2xl font-extrabold">Verified memory sales</h2><p className="mt-1 text-sm text-muted-foreground">Select a settled agent transfer to inspect its provenance certificate.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-success/30 bg-success/10 px-3 py-1.5 text-xs font-bold text-success"><ShieldCheck className="h-4 w-4"/>{provenanceSales.length} verified sales</span></header>
    <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b border-border bg-secondary/70 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Seller agent</th><th className="px-5 py-3">Buyer agent</th><th className="px-5 py-3">Provenance sold</th><th className="px-5 py-3">Value</th><th className="px-5 py-3">Status</th><th className="w-10 px-3 py-3"><span className="sr-only">Details</span></th></tr></thead><tbody>{provenanceSales.map(sale => {
      const open = selected === sale.listingId;
      return <Fragment key={sale.listingId}><tr tabIndex={0} role="button" aria-expanded={open} onClick={() => setSelected(open ? null : sale.listingId)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(open ? null : sale.listingId); } }} className="cursor-pointer border-b border-border transition hover:bg-primary/5 focus:bg-primary/5 focus:outline-none"><td className="px-5 py-4 font-mono text-xs font-bold text-foreground">{sale.sellerAgent}</td><td className="px-5 py-4 font-mono text-xs font-bold text-foreground">{sale.buyerAgent}</td><td className="px-5 py-4"><span className="font-semibold text-foreground">Full package</span><span className="ml-2 text-xs text-muted-foreground">6 categories · {sale.records} records</span></td><td className="px-5 py-4 font-mono text-xs font-bold">{sale.amount}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 rounded-full border border-success/30 bg-success/10 px-2.5 py-1 text-xs font-bold text-success"><span className="h-1.5 w-1.5 rounded-full bg-current"/>Verified</span></td><td className="px-3 py-4"><ChevronDown className={"h-4 w-4 transition " + (open ? "rotate-180" : "")}/></td></tr>{open && <tr className="border-b border-border bg-background/55"><td colSpan={6} className="p-5"><div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-extrabold uppercase text-muted-foreground">Transferred Sibyl categories</p><div className="mt-3 flex flex-wrap gap-2">{sale.categories.map(category => <span key={category} className="rounded-full border border-primary/25 bg-primary/10 px-3 py-1 text-xs font-semibold text-foreground">{category}</span>)}</div><dl className="mt-5 grid grid-cols-2 gap-3"><div><dt className="text-xs text-muted-foreground">Records</dt><dd className="mt-1 font-mono font-bold">{sale.records}</dd></div><div><dt className="text-xs text-muted-foreground">Memory version</dt><dd className="mt-1 font-mono font-bold">v{sale.memoryVersion}</dd></div><div><dt className="text-xs text-muted-foreground">Listing</dt><dd className="mt-1 font-mono text-xs font-bold">{sale.listingId}</dd></div><div><dt className="text-xs text-muted-foreground">Settled</dt><dd className="mt-1 text-xs font-bold">{sale.settledAt}</dd></div></dl></div><div className="space-y-3"><Detail label="Seller wallet" value={sale.sellerWallet}/><Detail label="Buyer wallet" value={sale.buyerWallet}/><Detail label="Verified Merkle root" value={sale.root}/><a onClick={event => event.stopPropagation()} href={"https://sepolia.basescan.org/tx/" + sale.transaction} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">Open settlement on BaseScan <ExternalLink className="h-4 w-4"/></a></div></div></td></tr>}</Fragment>;
    })}</tbody></table></div>
  </section>;
}

function Detail({ label, value }: { label: string; value: string }) {
  return <div className="rounded-md border border-border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><code className="mt-1 block break-all font-mono text-xs font-semibold text-foreground" title={value}>{short(value)}</code></div>;
}
